# NOTE: Generated By HttpRunner v3.1.1
# FROM: har\login.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login.action")
            .post("http://www.1123.com/login.action")
            .with_headers(
                **{
                    "Host": "www.1123.com",
                    "Connection": "keep-alive",
                    "Content-Length": "59",
                    "Accept": "*/*",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Origin": "http://www.1123.com",
                    "Referer": "http://www.1123.com/login.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "ovo_language=zh-CN; currLogin=1; RemenberPSW=1; Hm_lvt_66c19a404e94b9d61a2bb7f6acb7d642=1596555678,1596679992,1596788554,1597887746; NameList=mcc%2Cdpp%2Cmcc%2Clppz%2Croot%2Cwangjiangchao%2Clshm-px%2Cysdz01%2Cysmg%2Ctest_mc%2Cjmwrw%2Cgyq7%2Csuper_zzj%2Cqwnrw%2Cbt; JSESSIONID=B5E2D385DC7E5EA1663F342A74D5BCEE; UserName=mcc; Password=c33367701511b4f6020ec61ded352059; zg_did=%7B%22did%22%3A%20%22173705caef41fd-0b64e6fe570caa-b7a1334-1fa400-173705caef56be%22%7D; zg_336f3e9bb82c4b71a6ea422cff567d59=%7B%22sid%22%3A%201598255923060%2C%22updated%22%3A%201598255923060%2C%22info%22%3A%201597885098661%2C%22superProperty%22%3A%20%22%7B%5C%22%E5%BA%94%E7%94%A8%E5%90%8D%E7%A7%B0%5C%22%3A%20%5C%22%E8%AF%B8%E8%91%9Bio%5C%22%7D%22%2C%22platform%22%3A%20%22%7B%7D%22%2C%22utm%22%3A%20%22%7B%7D%22%2C%22referrerDomain%22%3A%20%22www.1123.com%22%2C%22zs%22%3A%200%2C%22sc%22%3A%200%2C%22firstScreen%22%3A%201598255923060%7D",
                }
            )
            .with_cookies(
                **{
                    "ovo_language": "zh-CN",
                    "currLogin": "1",
                    "RemenberPSW": "1",
                    "Hm_lvt_66c19a404e94b9d61a2bb7f6acb7d642": "1596555678,1596679992,1596788554,1597887746",
                    "NameList": "mcc%2Cdpp%2Cmcc%2Clppz%2Croot%2Cwangjiangchao%2Clshm-px%2Cysdz01%2Cysmg%2Ctest_mc%2Cjmwrw%2Cgyq7%2Csuper_zzj%2Cqwnrw%2Cbt",
                    "JSESSIONID": "B5E2D385DC7E5EA1663F342A74D5BCEE",
                    "UserName": "mcc",
                    "Password": "c33367701511b4f6020ec61ded352059",
                    "zg_did": "%7B%22did%22%3A%20%22173705caef41fd-0b64e6fe570caa-b7a1334-1fa400-173705caef56be%22%7D",
                    "zg_336f3e9bb82c4b71a6ea422cff567d59": "%7B%22sid%22%3A%201598255923060%2C%22updated%22%3A%201598255923060%2C%22info%22%3A%201597885098661%2C%22superProperty%22%3A%20%22%7B%5C%22%E5%BA%94%E7%94%A8%E5%90%8D%E7%A7%B0%5C%22%3A%20%5C%22%E8%AF%B8%E8%91%9Bio%5C%22%7D%22%2C%22platform%22%3A%20%22%7B%7D%22%2C%22utm%22%3A%20%22%7B%7D%22%2C%22referrerDomain%22%3A%20%22www.1123.com%22%2C%22zs%22%3A%200%2C%22sc%22%3A%200%2C%22firstScreen%22%3A%201598255923060%7D",
                }
            )
            .with_data(
                {"username": "mcc", "password": "c33367701511b4f6020ec61ded352059"}
            )
            .extract()
            .with_jmespath("body.token", "token")  # 提取出目标值，赋值给username变量
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain;charset=UTF-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
